name: Continuous Integration

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  ci:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.23

      - name: run integration test
        run: earthly --ci --verbose +integration-test

      - name: run integration image test
        run: earthly --ci --verbose --allow-privileged +integration-image-test

  ci-images:
    name: Build ${{ matrix.platform }} image
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: linux/arm64
          - os: ubuntu-latest
            platform: linux/amd64
    steps:
      - uses: actions/checkout@v3
        with:
          submodule: recursive

      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.23

      - name: build
        run: earthly --ci --verbose --platform ${{ matrix.platform }} +image --IMAGE_TAG="development"
